iaasapp/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
 
 
app = Flask(__name__)
app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///test.db'
app.config['WTF_CSRF_SECRET_KEY'] = 'asecretkey'
app.config['LDAP_PROVIDER'] = '192.168.0.153'
app.config['LDAP_PROTOCOL_VERSION'] = 3
app.config['VCSA_ADDRESS'] = '192.168.0.155'
app.config['CUSTOMER'] = 'Cloudis Consulting'
db = SQLAlchemy(app)
 
app.secret_key = 'verysecretkey'
 
login_manager = LoginManager()
login_manager.init_app(app)
login_manager.login_view = 'login'
 
from iaasapp.auth.views import auth
from iaasapp.vmoperations.views import vmoperations
app.register_blueprint(auth)
app.register_blueprint(vmoperations)

db.create_all()

iaasapp/vmoperations/views.py
from flask import request, render_template, flash, redirect, \
    url_for, Blueprint, g
from flask_login import current_user, login_required
from .npiaasvmware import *
from iaasapp import app

vmoperations = Blueprint('vmoperations', __name__)

@vmoperations.route('/vmlist')
@login_required
def vmlist():
    handler = npiaasvmware(server=app.config['VCSA_ADDRESS'],
                            username=current_user.username + '@cloudisatger.lan',
                            password=current_user.password,
                            customer=app.config['CUSTOMER'])
    try:
        result = handler.listVM()
    except customerNotFound:
        written = "Customer {} not found".format(app.config['CUSTOMER'])
    else:
        written = ""
        for vm in result:
            written += "\n\n"
            written += "Name       : {}\n".format(vm['name'])
            written += "Template   : {}\n".format(vm['template'])
            written += "OS         : {}\n".format(vm['os'])
            written += "State      : {}\n".format(vm['state'])
            written += "VMTools    : {}\n".format(vm['vmtools'])
            written += "IP         : {}\n".format(vm['ip'])
            written += "Last bkp   : {}\n".format(vm['lastsnap'])

    return render_template('vmlist.html', list=written, customer=app.config['CUSTOMER'])

@vmoperations.route('/vmrestart')
@login_required
def vmrestart():
    return render_template('vmoperation.html')

@vmoperations.route('/vmdelete')
@login_required
def vmdelete():
    return render_template('vmoperation.html')

iaasapp/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>NP-IAAS-WEB</title>
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet">
    <link href="{{ url_for('static', filename='css/main.css') }}" rel="stylesheet">
  </head>
  <body>
    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <a class="navbar-brand" href="{{ url_for('auth.home') }}">NP-IAAS-WEB</a>
        </div>
      </div>
    </div>
    <div class="container">
    <br/>
    <div>
      {% for category, message in get_flashed_messages(with_categories=true) %}
        <div class="alert alert-{{category}} alert-dismissable">
          <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
          {{ message }}
        </div>
      {% endfor %}
      </div>
    {% block container %}{% endblock %}
    </div>
 
    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.0.0/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
    {% block scripts %}
    {% endblock %}
  </body>
</html>

iaasapp/templates/home.html
{% extends 'base.html' %}
 
{% block container %}
  <h1>NP-IAAS-WEB</h1>
  {% if current_user.is_authenticated %}
    <h3>Greetings {{ current_user.username }}</h3>
    <a class="btn btn-primary" href="{{ url_for('vmoperations.vmlist') }}">VM List</a>
    <a class="btn btn-warning" href="{{ url_for('vmoperations.vmrestart') }}">Restart VM</a>
    <a class="btn btn-warning" href="{{ url_for('vmoperations.vmdelete') }}">Delete VM</a>
    <br /><br />
    <a class="btn btn-danger" href="{{ url_for('auth.logout') }}">Logout</a>
  {% else %}
  <a class="btn btn-primary" href="{{ url_for('auth.login') }}">Log in with Active Directory</a>
  {% endif %}
{% endblock %}

iaasapp/templates/login.html
{% extends 'home.html' %}
 
{% block container %}
  <div class="top-pad">
    <form
        method="POST"
        action="{{ url_for('auth.login') }}"
        role="form">
      {{ form.csrf_token }}
      <div class="form-group">{{ form.username.label }}: {{ form.username() }}</div>
      <div class="form-group">{{ form.password.label }}: {{ form.password() }}</div>
      <button type="submit" class="btn btn-primary">Submit</button>
    </form>
  </div>
{% endblock %}

iaasapp/templates/vmlist.html
{% extends 'base.html' %}
 
{% block container %}
  <h1>VM List for customer {{ customer }}</h1>
  <div class="top-pad">
    <pre>{{ list }}</pre>
  </div>
{% endblock %}

iaasapp/templates/vmoperation.html
{% extends 'base.html' %}
 
{% block container %}
  <h1>VM operation for customer {{ customer }}</h1>
  <div class="top-pad">
    <p>Not implemented :(</p>
  </div>
{% endblock %}